FROM apache/airflow:2.7.2-python3.10

USER airflow

RUN python -m pip install --upgrade pip

COPY dags/data/ /opt/airflow/data/

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt