FROM bitnami/spark:3.4.1

USER root

ARG SPARK_UID=1001
ARG SPARK_GID=1001
RUN groupadd -g ${SPARK_GID} spark || true && \
    useradd -m -u ${SPARK_UID} -g ${SPARK_GID} -s /bin/bash spark || true

RUN mkdir -p /tmp/.ivy2 /opt/spark/work-dir && \
    chown -R ${SPARK_UID}:${SPARK_GID} /tmp/.ivy2 /opt/spark /opt/bitnami/spark

ENV USER=spark \
    HADOOP_USER_NAME=spark \
    SPARK_USER=spark \
    SPARK_SUBMIT_OPTS="-Duser.name=spark" \
    JAVA_TOOL_OPTIONS="-Duser.name=spark"

USER spark